apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: testreg1130.azurecr.io/delivery:latest
          ports:
            - containerPort: 8080

          livenessProbe:
            tcpSocket:
              #path: '/actuator/health'
              port: 8081
            initialDelaySeconds: 15
            #timeoutSeconds: 2
            periodSeconds: 20
            #failureThreshold: 5

